server.port=8089
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://cockroachdb:26257/mydb?sslmode=verify-full&sslrootcert=/app/certs/ca.crt}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:appuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:appuser}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.datasource.driver-class-name=org.postgresql.Driver

myapp.local.app.admin.credentials.secret.key=my-app-secret
cloud.aws.credentials.profile-name=local-app
cloud.aws.region.static=us-east-1
logging.level.com.sc=debug
logging.level.org.springframework.security=debug