apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartworker-web-ingress
  namespace: smartworker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: smartworker.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smartworker-web
            port:
              number: 80